#pragma once

#include "types.hpp"
#include <concepts>
#include <compare>

namespace kstd {
    template<typename T>
    constexpr T&& move(T &value) {
        return static_cast<T&&>(value);
    }

    template<typename T>
    struct remove_reference {
        using type = T;
    };

    template<typename T>
    struct remove_reference<T&> {
        using type = T;
    };

    template<typename T>
    struct remove_reference<T&&> {
        using type = T;
    };

    template<typename T>
    using remove_reference_t = typename remove_reference<T>::type;

    template<typename T>
    struct remove_const {
        using type = T;
    };

    template<typename T>
    struct remove_const<const T> {
        using type = T;
    };

    template<typename T>
    using remove_const_t = typename remove_const<T>::type;

    // -- Autogenerated --
    // TODO: Format it
    template<typename T> struct remove_cv { using type = T; };
    template<typename T> struct remove_cv<const T> { using type = T; };
    template<typename T> struct remove_cv<volatile T> { using type = T; };
    template<typename T> struct remove_cv<const volatile T> { using type = T; };
    // -- Till here ^ --

    template<typename T>
    using remove_cv_t = typename remove_cv<T>::type;

    template<typename T>
    struct remove_cvref {
        using type = remove_cv_t<remove_reference_t<T>>;
    };

    template<typename T>
    using remove_cvref_t = typename remove_cvref<T>::type;

    template<typename T>
    constexpr T&& forward(remove_reference_t<T> &arg) noexcept {
        return static_cast<T&&>(arg);
    }

    template<typename T>
    constexpr void swap(T &x, T &y) noexcept {
        T temp = kstd::move(x);
        x = kstd::move(y);
        y = kstd::move(temp);
    }

    template<typename T, typename U>
    struct is_same {
        static constexpr bool value = false;
    };

    template<typename T>
    struct is_same<T, T> {
        static constexpr bool value = true;
    };

    template<typename T, typename U>
    inline constexpr bool is_same_v = is_same<T, U>::value;

    template<typename T>
    struct is_array {
        static constexpr bool value = false;
    };

    template<typename T>
    struct is_array<T[]> {
        static constexpr bool value = true;
    };
 
    template<typename T, size_t N>
    struct is_array<T[N]> {
        static constexpr bool value = true;
    };

    template<typename T>
    inline constexpr bool is_array_v = is_array<T>::value;

    template<typename T>
    struct type_identity {
        using type = T;
    };

    template<typename T>
    using type_identity_t = typename type_identity<T>::type;

    // Not-standard
    // Credits: https://youtube.com/watch?v=SmlLdd1Q2V8
    template<typename Destination>
    constexpr Destination implicit_cast(type_identity_t<Destination> src) noexcept {
        return src;
    }

    // Not-standard, alias to bit_cast
    // Credits: https://youtube.com/watch?v=SmlLdd1Q2V8
    template<typename Destination, typename Source>
    constexpr Destination pun_cast(const Source &val) noexcept {
        static_assert(sizeof(Destination) == sizeof(Source));
        return __builtin_bit_cast(Destination, val);
    }

    template<typename Destination, typename Source>
    constexpr Destination bit_cast(const Source &val) noexcept {
        static_assert(sizeof(Destination) == sizeof(Source));
        return __builtin_bit_cast(Destination, val);
    }

    template<typename T, typename U>
    struct pair {
        T first;
        U second;

        auto operator<=>(const pair &other) const noexcept = default;
        bool operator==(const pair &other) const noexcept = default;
        pair& operator=(const pair &other) noexcept {
            if (this == &other) return *this;

            this->first = other.first;
            this->second = other.second;

            return *this;
        }
        pair& operator=(pair &&other) noexcept
        requires std::move_constructible<T> && 
                 std::move_constructible<U>
        {
            if (this == &other) return *this;

            this->first = kstd::move(other.first);
            this->second = kstd::move(other.second);

            return *this;
        }

        pair() = default;
        pair(const pair &other) : first(other.first)
                                , second(other.second)
        {}
        pair(pair &&other) : first(kstd::move(other.first))
                           , second(kstd::move(other.second))
        {}
        pair(const T &first, const U &second) : first(first)
                                              , second(second) 
        {}
        pair(T &&first, U &&second) : first(kstd::move(first))
                                    , second(kstd::move(second)) 
        {}
        ~pair() = default;
    };

    template<typename... Ts>
    struct tuple;

    template<>
    struct tuple<> {};

    namespace detail {
        template<size_t Index, typename T, typename... Ts>
        constexpr const T& tuple_get(const tuple<Ts...> &tuple) noexcept;
    }

    template<typename T, typename... Ts>
    struct tuple<T, Ts...> {
    public:
        // TODO: Get a better way to do this aka make these private
        T __val;
        tuple<Ts...> __rest;
    public:
        tuple& operator=(const tuple &other) = default;
        tuple& operator=(tuple &&other) = default;
    public:
        tuple() = default;
        tuple(const tuple &other) = default;
        tuple(tuple &&other) = default;
    };

    template<size_t Index, typename T, typename U>
    constexpr auto get(const pair<T, U> &p) noexcept {
        if constexpr (Index == 0) {
            return p.first;
        } else if constexpr (Index == 1) {
            return p.second;
        }
    }

    template<typename T, typename U>
    constexpr const T& get(const pair<T, U> &p) noexcept {
        return p.first;
    }

    namespace detail {
        template<size_t Index, typename... Ts>
        constexpr const auto& tuple_get(const tuple<Ts...> &tuple) noexcept {
            if constexpr (Index == 0) {
                return tuple.__val;
            } else {
                return tuple_get<Index - 1>(tuple.__rest);
            }
        }
    }

    template<typename U, typename T>
    constexpr const U& get(const pair<T, U> &p) noexcept {
        return p.second;
    }

    template<size_t Index, typename... Ts>
    constexpr const auto& get(const tuple<Ts...> &tuple) noexcept {
        return detail::tuple_get<Index, Ts...>(tuple);
    }

    template<typename T, typename U>
    constexpr pair<T, U> make_pair(const T &first, const U &second) noexcept {
        return pair<T, U> { first, second };
    }

    template<typename T, typename U>
    constexpr pair<T, U> make_pair(T &&first, U &&second) noexcept {
        return pair<T, U> { forward<T>(first), forward<U>(second) };
    }

    template<typename... Ts>
    constexpr tuple<Ts...> make_tuple(const Ts&... args) noexcept {
        return tuple<Ts...> { args... };
    }

    template<typename... Ts>
    constexpr tuple<Ts...> make_tuple(Ts&&... args) {
        return tuple<Ts...> { forward<Ts>(args)... };
    }
}
